#!/usr/bin/env python3
"""Keep each wiki PR in step with the code PR that spawned it.

A wiki PR opened by scripts/wiki-pr.sh carries a `Source: <code PR url>` trailer. This
walks the open ones and reconciles them against their source:

    source merged            -> mark ready, merge
    source closed unmerged   -> close
    source open > 7 days     -> nudge both, once
    no source trailer        -> leave alone (hand-written wiki PR)

Runs on a schedule rather than off webhooks so a missed event self-heals on the next pass.

Usage:
    python3 scripts/wiki_pr_lifecycle.py [--dry-run]

Requires `gh` authenticated with read access to the code repos and write access here.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone

WIKI_REPO = "helloallytech/helloallytech.github.io"
SOURCE_TRAILER = re.compile(
    r"^\s*Source:\s*(https://github\.com/([^/\s]+)/([^/\s]+)/pull/(\d+))\s*$",
    re.MULTILINE | re.IGNORECASE,
)
NUDGE_MARKER = "<!-- wiki-pr-lifecycle:nudged -->"
STALE_AFTER = timedelta(days=7)

FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


def gh(*args: str) -> str:
    result = subprocess.run(
        ["gh", *args], capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        raise RuntimeError(f"gh {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def gh_json(*args: str):
    return json.loads(gh(*args) or "null")


def open_wiki_prs() -> list[dict]:
    return gh_json(
        "pr", "list", "--repo", WIKI_REPO, "--state", "open",
        "--limit", "100", "--json", "number,title,body,createdAt,isDraft,comments",
    ) or []


def source_of(body: str):
    m = SOURCE_TRAILER.search(body or "")
    if not m:
        return None
    return {"url": m.group(1), "repo": f"{m.group(2)}/{m.group(3)}", "number": m.group(4)}


def source_state(source: dict) -> dict | None:
    try:
        return gh_json(
            "pr", "view", source["number"], "--repo", source["repo"],
            "--json", "state,mergedAt,url",
        )
    except RuntimeError as exc:
        print(f"  ! could not read {source['url']}: {exc}", file=sys.stderr)
        return None


def already_nudged(pr: dict) -> bool:
    return any(NUDGE_MARKER in (c.get("body") or "") for c in pr.get("comments") or [])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    act = not args.dry_run
    now = datetime.now(timezone.utc)
    merged = closed = nudged = skipped = 0

    for pr in open_wiki_prs():
        num = str(pr["number"])
        source = source_of(pr.get("body", ""))
        if not source:
            skipped += 1
            continue

        print(f"wiki #{num} ← {source['url']}")
        state = source_state(source)
        if not state:
            continue

        if state.get("mergedAt"):
            print("  source merged → merging wiki PR")
            if act:
                if pr.get("isDraft"):
                    gh("pr", "ready", num, "--repo", WIKI_REPO)
                gh("pr", "merge", num, "--repo", WIKI_REPO, "--squash", "--delete-branch")
            merged += 1

        elif state.get("state") == "CLOSED":
            print("  source closed unmerged → closing wiki PR")
            if act:
                gh(
                    "pr", "close", num, "--repo", WIKI_REPO, "--delete-branch",
                    "--comment",
                    f"Closing: the source PR {source['url']} was closed without "
                    "merging, so these docs describe a change that never shipped."
                    + FOOTER,
                )
            closed += 1

        else:
            created = datetime.fromisoformat(pr["createdAt"].replace("Z", "+00:00"))
            age = now - created
            if age > STALE_AFTER and not already_nudged(pr):
                days = age.days
                print(f"  source open {days}d → nudging")
                if act:
                    gh(
                        "pr", "comment", num, "--repo", WIKI_REPO, "--body",
                        f"{NUDGE_MARKER}\nThis wiki PR has been open **{days} days** "
                        f"waiting on {source['url']}.\n\nDocs that sit in an unmerged PR "
                        "are the drift this coupling exists to prevent — land the source "
                        "PR, or close both." + FOOTER,
                    )
                    gh(
                        "pr", "comment", source["number"], "--repo", source["repo"],
                        "--body",
                        f"{NUDGE_MARKER}\nThe wiki PR for this change "
                        f"(https://github.com/{WIKI_REPO}/pull/{num}) has been waiting "
                        f"**{days} days** to merge alongside it." + FOOTER,
                    )
                nudged += 1
            else:
                print("  source still open → waiting")

    print(
        f"\nmerged={merged} closed={closed} nudged={nudged} "
        f"no-source={skipped}{' (dry run)' if args.dry_run else ''}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
