#!/usr/bin/env python3
"""Keep each wiki PR in step with the code change that spawned it.

A wiki PR opened by scripts/wiki-pr.sh carries a `Source:` trailer naming either a code PR
or a commit — most changes on this platform are pushed straight to the default branch, so
both have to work. This walks the open wiki PRs and reconciles them against their source:

    source PR merged             -> mark ready, merge
    source commit on default     -> mark ready, merge
    source PR closed unmerged    -> close
    source pending > 7 days      -> nudge, once
    no source trailer            -> leave alone (hand-written wiki PR)

A commit source has no counterpart to nudge, so those nudges land on the wiki PR only.

Runs on a schedule rather than off webhooks so a missed event self-heals on the next pass.

Usage:
    python3 scripts/wiki_pr_lifecycle.py [--dry-run]

Requires `gh` authenticated with read access to the code repos and write access here.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone

WIKI_REPO = "helloallytech/helloallytech.github.io"
SOURCE_TRAILER = re.compile(
    r"^\s*Source:\s*(https://github\.com/([^/\s]+)/([^/\s]+)/"
    r"(?:pull/(\d+)|commit/([0-9a-f]{7,40})))\s*$",
    re.MULTILINE | re.IGNORECASE,
)
NUDGE_MARKER = "<!-- wiki-pr-lifecycle:nudged -->"
STALE_AFTER = timedelta(days=7)

FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


def gh(*args: str) -> str:
    result = subprocess.run(
        ["gh", *args], capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        raise RuntimeError(f"gh {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def gh_json(*args: str):
    return json.loads(gh(*args) or "null")


def open_wiki_prs() -> list[dict]:
    return gh_json(
        "pr", "list", "--repo", WIKI_REPO, "--state", "open",
        "--limit", "100",
        "--json", "number,title,body,createdAt,isDraft,comments,isCrossRepository",
    ) or []


def branch_args(pr: dict) -> list[str]:
    """`--delete-branch`, unless the branch lives in someone's fork.

    Most contributors have no write access here and open their wiki PR from a fork. We
    cannot delete a branch in their personal repo, and gh treats the refusal as an error —
    which would abort the whole reconciliation pass over one tidy-up we never needed.
    """
    return [] if pr.get("isCrossRepository") else ["--delete-branch"]


def source_of(body: str):
    m = SOURCE_TRAILER.search(body or "")
    if not m:
        return None
    source = {"url": m.group(1), "repo": f"{m.group(2)}/{m.group(3)}"}
    if m.group(4):
        source.update(kind="pr", ref=m.group(4))
    else:
        source.update(kind="commit", ref=m.group(5))
    return source


def verdict(source: dict) -> str | None:
    """`landed`, `abandoned` or `pending` — or None if the source cannot be read."""
    if source["kind"] == "pr":
        try:
            state = gh_json(
                "pr", "view", source["ref"], "--repo", source["repo"],
                "--json", "state,mergedAt,url",
            )
        except RuntimeError as exc:
            print(f"  ! could not read {source['url']}: {exc}", file=sys.stderr)
            return None
        if state.get("mergedAt"):
            return "landed"
        return "abandoned" if state.get("state") == "CLOSED" else "pending"

    # A commit source has landed once it is reachable from the default branch. Comparing
    # default...sha reports the sha as `behind` when it is an ancestor, `identical` when it
    # is the tip, and `ahead`/`diverged` while it still sits on a side branch.
    try:
        default = gh(
            "repo", "view", source["repo"],
            "--json", "defaultBranchRef", "-q", ".defaultBranchRef.name",
        ).strip()
        compared = gh_json(
            "api", f"repos/{source['repo']}/compare/{default}...{source['ref']}",
        )
    except RuntimeError as exc:
        print(f"  ! could not read {source['url']}: {exc}", file=sys.stderr)
        return None
    return "landed" if compared.get("status") in ("identical", "behind") else "pending"


def already_nudged(pr: dict) -> bool:
    return any(NUDGE_MARKER in (c.get("body") or "") for c in pr.get("comments") or [])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    act = not args.dry_run
    now = datetime.now(timezone.utc)
    merged = closed = nudged = skipped = 0

    for pr in open_wiki_prs():
        num = str(pr["number"])
        source = source_of(pr.get("body", ""))
        if not source:
            skipped += 1
            continue

        print(f"wiki #{num} ← {source['url']}")
        state = verdict(source)
        if not state:
            continue

        if state == "landed":
            print("  source landed → merging wiki PR")
            if act:
                if pr.get("isDraft"):
                    gh("pr", "ready", num, "--repo", WIKI_REPO)
                gh("pr", "merge", num, "--repo", WIKI_REPO, "--squash", *branch_args(pr))
            merged += 1

        elif state == "abandoned":
            print("  source closed unmerged → closing wiki PR")
            if act:
                gh(
                    "pr", "close", num, "--repo", WIKI_REPO, *branch_args(pr),
                    "--comment",
                    f"Closing: the source PR {source['url']} was closed without "
                    "merging, so these docs describe a change that never shipped."
                    + FOOTER,
                )
            closed += 1

        else:
            created = datetime.fromisoformat(pr["createdAt"].replace("Z", "+00:00"))
            age = now - created
            if age > STALE_AFTER and not already_nudged(pr):
                days = age.days
                print(f"  source pending {days}d → nudging")
                if act:
                    waiting_on = (
                        f"the source PR {source['url']}"
                        if source["kind"] == "pr"
                        else f"commit {source['ref'][:7]} to reach "
                        f"{source['repo']}'s default branch ({source['url']})"
                    )
                    gh(
                        "pr", "comment", num, "--repo", WIKI_REPO, "--body",
                        f"{NUDGE_MARKER}\nThis wiki PR has been open **{days} days** "
                        f"waiting on {waiting_on}.\n\nDocs that sit in an unmerged PR "
                        "are the drift this coupling exists to prevent — land the source, "
                        "or close both." + FOOTER,
                    )
                    # A commit has no PR to comment on; the wiki-side nudge is the whole
                    # nudge in that case.
                    if source["kind"] == "pr":
                        gh(
                            "pr", "comment", source["ref"], "--repo", source["repo"],
                            "--body",
                            f"{NUDGE_MARKER}\nThe wiki PR for this change "
                            f"(https://github.com/{WIKI_REPO}/pull/{num}) has been waiting "
                            f"**{days} days** to merge alongside it." + FOOTER,
                        )
                nudged += 1
            else:
                print("  source still pending → waiting")

    print(
        f"\nmerged={merged} closed={closed} nudged={nudged} "
        f"no-source={skipped}{' (dry run)' if args.dry_run else ''}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
