#!/usr/bin/env bash
# Open a wiki PR for documentation changes made alongside a code change.
#
# Updating the wiki used to mean cloning a second repo and hand-rolling a second PR. That
# friction is why platform pages sat unchanged for a month while the code moved daily.
# This makes it one command.
#
# Usage, from any code repo:
#
#   git clone --depth=1 https://github.com/helloallytech/helloallytech.github.io .wiki-tmp
#   # edit .wiki-tmp/wiki/**
#   .wiki-tmp/scripts/wiki-pr.sh "https://github.com/helloallytech/ally-be/pull/123"
#
# Prints the `Wiki-PR:` trailer to paste into your code PR description. That trailer is
# what satisfies the docs guard, and what couples the two PRs' lifecycles.
#
# Spec: https://tech.helloally.ai/#/wiki/contributing/docs-system.md

set -euo pipefail

SOURCE_PR="${1:-}"
WIKI_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

die() { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }
info() { printf '\033[36m%s\033[0m\n' "$*"; }

if [[ -z "$SOURCE_PR" ]]; then
  die "pass the URL of the code PR these docs belong to:
    $(basename "${BASH_SOURCE[0]}") \"https://github.com/helloallytech/<repo>/pull/<n>\""
fi

if [[ ! "$SOURCE_PR" =~ ^https://github\.com/[^/]+/[^/]+/pull/[0-9]+/?$ ]]; then
  die "that doesn't look like a PR URL: $SOURCE_PR"
fi

cd "$WIKI_ROOT"
[[ -d wiki ]] || die "no wiki/ directory here — is $WIKI_ROOT really the wiki clone?"

SOURCE_REPO="$(printf '%s' "$SOURCE_PR" | awk -F/ '{print $5}')"
SOURCE_NUM="$(printf '%s' "$SOURCE_PR" | awk -F/ '{print $7}' | tr -d '/')"
BRANCH="docs/from-${SOURCE_REPO}-pr-${SOURCE_NUM}"

# A shallow clone can't push a branch history; deepen before we try.
if [[ -f .git/shallow ]]; then
  info "Deepening shallow clone…"
  git fetch --unshallow --quiet origin || git fetch --depth=50 --quiet origin
fi

if [[ -x scripts/gen-routing.py ]] || [[ -f scripts/gen-routing.py ]]; then
  info "Regenerating the routing index…"
  python3 scripts/gen-routing.py >/dev/null
fi

if git diff --quiet && git diff --cached --quiet && [[ -z "$(git status --porcelain wiki)" ]]; then
  die "no changes under wiki/ — edit a page first."
fi

info "Changed:"
git status --porcelain wiki | sed 's/^/  /'

git config user.name  >/dev/null 2>&1 || git config user.name  "ally-docs"
git config user.email >/dev/null 2>&1 || git config user.email "ally-docs@users.noreply.github.com"

git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"
git add wiki
git commit --quiet -m "docs: update wiki for ${SOURCE_REPO}#${SOURCE_NUM}

Source: ${SOURCE_PR}"

info "Pushing $BRANCH…"
for attempt in 1 2 3 4; do
  if git push -u origin "$BRANCH" --quiet; then break; fi
  [[ $attempt -eq 4 ]] && die "push failed after 4 attempts"
  sleep $((2 ** attempt))
done

BODY="Documentation for ${SOURCE_REPO}#${SOURCE_NUM}.

Source: ${SOURCE_PR}

This PR is coupled to its source: it is marked ready and merged when the source PR merges,
and closed if the source PR is closed unmerged. See
[the docs system](https://tech.helloally.ai/#/wiki/contributing/docs-system.md).

---
_Generated by [Claude Code](https://claude.ai/code)_"

if command -v gh >/dev/null 2>&1; then
  PR_URL="$(gh pr create --draft \
    --title "docs: update wiki for ${SOURCE_REPO}#${SOURCE_NUM}" \
    --body "$BODY" --head "$BRANCH" 2>/dev/null || gh pr view "$BRANCH" --json url -q .url)"
else
  info "gh not installed — open the PR manually:"
  echo "  https://github.com/helloallytech/helloallytech.github.io/compare/$BRANCH?expand=1"
  echo "  and include this line in the body:  Source: ${SOURCE_PR}"
  PR_URL="<paste the wiki PR url here>"
fi

cat <<EOF

────────────────────────────────────────────────────────────
Paste this into the description of ${SOURCE_PR}:

Wiki-PR: ${PR_URL}
────────────────────────────────────────────────────────────
EOF
